name: Build Android Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-31" "build-tools;31.0.0" "platform-tools"
        env:
          ANDROID_HOME: ${{ env.HOME }}/android-sdk

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
          ANDROID_HOME: ${{ env.HOME }}/android-sdk
          ANDROID_SDK_ROOT: ${{ env.HOME }}/android-sdk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: |
            MyAndroidApp/app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release.apk
