name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Create Gradle Wrapper
      run: |
        echo '#!/usr/bin/env sh' > gradlew
        echo 'exec gradle "$@"' >> gradlew
        chmod +x gradlew
        
    - name: Create gradle-wrapper.properties
      run: |
        mkdir -p gradle/wrapper
        echo 'distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip' > gradle/wrapper/gradle-wrapper.properties
        
    - name: Create settings.gradle
      run: |
        echo "rootProject.name = 'automation'" > settings.gradle
        
    - name: Create build.gradle
      run: |
        echo """
        plugins {
            id 'com.android.application'
            id 'kotlin-android'
        }
        
        android {
            compileSdkVersion 30
            
            defaultConfig {
                applicationId "com.example.automation"
                minSdkVersion 21
                targetSdkVersion 30
                versionCode 1
                versionName "1.0"
            }
            
            buildTypes {
                release {
                    minifyEnabled false
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                }
            }
        }
        
        dependencies {
            implementation "org.jetbrains.kotlin:kotlin-stdlib:1.5.0"
            implementation 'androidx.core:core-ktx:1.3.2'
            implementation 'androidx.appcompat:appcompat:1.2.0'
        }
        """ > build.gradle
        
    - name: List directory contents
      run: ls -la
        
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
